/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.bios;

import br.com.DAO.ConexaoDAO;
import br.com.DAO.UsuarioDAO;
import br.com.dto.UsuarioDto;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Leon
 */
public class telaUsuarios extends javax.swing.JFrame {

    /**
     * Creates new form telaUsuarios
     */
    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    public telaUsuarios() {
        initComponents();
        conexao = ConexaoDAO.connector();
        ImageIcon pesq = new ImageIcon("src/img/search.png");
        btnPesq.setIcon(pesq);

        ImageIcon rem = new ImageIcon("src/img/remove.png");
        btnLimp.setIcon(rem);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")


    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUsu = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        btnPesq = new javax.swing.JButton();
        btnLimp = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtLog = new javax.swing.JTextField();
        txtPass = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TelaUsuarios");
        setResizable(false);

        jLabel1.setText("ID");

        jLabel2.setText("nome");

        btnPesq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesqActionPerformed(evt);
            }
        });

        btnLimp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpActionPerformed(evt);
            }
        });

        jLabel3.setText("login");

        jLabel4.setText("senha");

        btnAdd.setText("inserir");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnExcluir.setText("excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        jButton1.setText("alterar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1))
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUsu)
                            .addComponent(txtNome)
                            .addComponent(txtLog)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPass)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnPesq)
                                .addGap(40, 40, 40)
                                .addComponent(btnLimp)
                                .addGap(18, 18, 18)
                                .addComponent(btnAdd)
                                .addGap(0, 22, Short.MAX_VALUE)))))
                .addGap(9, 9, 9)
                .addComponent(btnExcluir)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(420, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtLog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnPesq)
                        .addComponent(btnLimp))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAdd)
                        .addComponent(btnExcluir)
                        .addComponent(jButton1)))
                .addContainerGap(277, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesqActionPerformed

        UsuarioDto objDto = new UsuarioDto();

        String senhaUsu = txtPass.getText();
        String logUsu = txtLog.getText();
        String nomeUsu = txtNome.getText();
        int idUsu = Integer.parseInt(txtUsu.getText());

        objDto.setIdUsu(idUsu);
        objDto.setLoginUsu(logUsu);
        objDto.setNomeUsu(nomeUsu);
        objDto.setSenhaUsu(senhaUsu);

        UsuarioDAO dao = new UsuarioDAO();

        dao.pesquisar(objDto);
                    }//GEN-LAST:event_btnPesqActionPerformed

    private void btnLimpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpActionPerformed
        UsuarioDAO dao = new UsuarioDAO();
        dao.limpar();
    }//GEN-LAST:event_btnLimpActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        if (txtUsu.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "preencha o campo de id");
        } else if (txtLog.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "preencha o campo de login");
        } else if (txtNome.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "preencha o campo de nome");
        } else if (txtPass.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "preencha o campo de senha");
        } else {

            int id_usu = Integer.parseInt(txtUsu.getText());
            String senha_usu = txtPass.getText();
            String login_usu = txtLog.getText();
            String nome_usu = txtNome.getText();

            UsuarioDto objUsuarioDto = new UsuarioDto();

            objUsuarioDto.setIdUsu(id_usu);
            objUsuarioDto.setLoginUsu(login_usu);
            objUsuarioDto.setNomeUsu(nome_usu);
            objUsuarioDto.setSenhaUsu(senha_usu);

            UsuarioDAO uDAO = new UsuarioDAO();
            uDAO.addUsu(objUsuarioDto);

            txtNome.setText(null);
            txtLog.setText(null);
            txtPass.setText(null);

    }//GEN-LAST:event_btnAddActionPerformed
    }
    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int id_usu = Integer.parseInt(txtUsu.getText());

        UsuarioDto objUsuarioDto = new UsuarioDto();

        objUsuarioDto.setIdUsu(id_usu);

        UsuarioDAO dao = new UsuarioDAO();
        dao.deletar(objUsuarioDto);
        dao.limpar();
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(txtUsu.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha o campo de ID");
        } else{
        
        UsuarioDto dto = new UsuarioDto();

        int id_usu = Integer.parseInt(txtUsu.getText());
        String senha_usu = txtPass.getText();
        String login_usu = txtLog.getText();
        String nome_usu = txtNome.getText();

        dto.setIdUsu(id_usu);
        dto.setLoginUsu(login_usu);
        dto.setNomeUsu(nome_usu);
        dto.setSenhaUsu(senha_usu);
        
        UsuarioDAO dao = new UsuarioDAO();
        dao.atualizar(dto);

    }//GEN-LAST:event_jButton1ActionPerformed
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLimp;
    private javax.swing.JButton btnPesq;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public static javax.swing.JTextField txtLog;
    public static javax.swing.JTextField txtNome;
    public static javax.swing.JTextField txtPass;
    public static javax.swing.JTextField txtUsu;
    // End of variables declaration//GEN-END:variables
}
